pipeline:
  identifier: Build_Ghoshaya1_LatencyCheck_1757944887704
  name: Build LatencyCheck
  orgIdentifier: default
  projectIdentifier: default
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1757944841506
        repoName: Ghoshaya1/LatencyCheck
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Arm64
            os: MacOS
          runtime:
            spec: {}
            type: Docker
        type: CI
